apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-actuator-deployment
spec:
  selector:
    matchLabels:
      app: endpoint-actuator
  replicas: 2
  template:
    metadata:
      labels:
        app: endpoint-actuator
    spec:
      containers:
        - name: endpoint-actuator
          image:  schimidt/endpoint-actuator:5.0.0

