apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-actuator-outro
spec:
  selector:
    matchLabels:
      app: endpoint-actuator-outro
  replicas: 5
  template:
    metadata:
      labels:
        app: endpoint-actuator
    spec:
      containers:
        - name: endpoint-actuator
          image:  ubuntu:18.04
          command: [ "/bin/sh" ]
          args: [ "-c", "while true; do echo hello; sleep 10;done" ]