apiVersion: v1
kind: Service
metadata:
  name: endpoint-actuator
  labels:
    app: endpoint-actuator
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: endpoint-actuator