apiVersion: v1
kind: Service
metadata:
  name: endpoint-actuator
  labels:
    app: endpoint-actuator
spec:
  type: LoadBalancer
  selector:
    app: endpoint-actuator
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: web
